### ISSUE TITLE
Whats going on with this fork

### ISSUE THREAD

**Issue by DKingCN** [Lykos153/mixxx#20]
Hi, I have been poking around with Roland DJ 202 these days and interested in Mixxx with DJ 202 compatibility. But this fork seems to be suspended since 6 months ago as well as in the upstream PRs list.

So whats going on and when will I possibly be luckily enough to try this in Mixxx?

**Comment by goosecoid** [comment]
also interested in knowing this.

**Comment by Lykos153** [comment]
Not much going on right now. I don't currently have the time for this. A whole lot is already working, though. Just copy over the 2 files (Roland_DJ-202.midi.xml and Roland_DJ-202-scripts.js in  res/controllers/) and try it yourselves. It shouldn't be that hard to modify it to your wishes and add more functionality from here on. (PRs still welcome)

What's still missing is the ability to sync to the playing song in order to actually use the sequencer. Unfortunately this can't be done inside the mapping alone, because Mixxx is still lacking some crucial features, see https://github.com/Lykos153/mixxx/issues/2

**Comment by goosecoid** [comment]
OK I understand. I already tried it and indeed it works kinda ok. Just can't get headphone output from the controller though. Anyways thank you for your work. Maybe if one day I have the time I'll make a pull request.

**Comment by Lykos153** [comment]
The headphone output is not related to the mapping. The DJ 202 presents itself as a sound card to the PC. So check your sound settings, as even without any mapping, sound output and input should work fine.

**Comment by DKingCN** [comment]
thanks for all the codes and configs
