### ISSUE TITLE
Stop LEDs from turning off after button release

### ISSUE THREAD

**Issue by Lykos153** [Lykos153/mixxx#3]
The DJ-202 seems to have a hardcoded behaviour for some buttons: The LED is turned off when the button is released. So for those buttons, the MIDI message needs to be resent on release. I'm currently working on this using modified Button objects.

Affected buttons are: Play, CUE, Sync, Keylock

Idk how common this is. Maybe this can be contributed to the components.js

**Comment by eigengrau** [comment]
I think all the LED issues should be addressed so far, though the implementation has not yet been factored into one underlying base class.

**Comment by Be-ing** [comment]
> Idk how common this is.

This is really weird. I have never heard of it on another controller. This is what happens when manufacturers hardcode application logic into controllers' firmware...

**Comment by Be-ing** [comment]
> In relation to this: this issue also arises when certain buttons are pressed in conjunction with the shift key. I mapped FX cycling to shift+FX1-3 yesterday (will open a PR later today) and noticed that the controller would disable the FX-focused LED for that button.

The Hercules P32 firmware also does this changing of LEDs when the shift button is pressed. I made the [sendShifted Component property](https://mixxx.org/wiki/doku.php/components_js#optional_properties) to work around this. This flickering of LEDs when pressing the shift button is bad UX design because shift buttons are pressed to access a variety of unrelated functions. For example, if you want to use the shift + play function and the effects button LEDs change when you press shift when you aren't thinking about effects, that creates a distraction. Here is another example of manufacturers creating hassles by baking application logic into controller firmware. :/

**Comment by eigengrau** [comment]
Yea, it’s a bit silly. Closing this for now, since I believe we have all the LED self-disable issues covered.
