### ISSUE TITLE
Add 4 deck support

### ISSUE THREAD

**Issue by Lykos153** [Lykos153/mixxx#6]
Adding 4 deck support is very easy using the components library, BUT:

While the [Deck 3/4] button is pressed, the DJ-202 sends on a different Channel. Using the trivial implementation for switching decks, the controls wouldn't work while the button is pressed.
We have 3 possibilities to deal with it:
* Accept it like that
* Work around this issue. To do this, we'd need to react on both channels (which is easy) but also send the messages on both channels. That would probably require some modification to the underlying compontents.
* Use the Deck button as a second shift. Then we'd need a mechanism for the Deck button to latch.

**Comment by eigengrau** [comment]
So, I was gonna write that I would really like the deck3/4 buttons to latch, but that I anticipate the pad section indicator LEDs to cause problems. The pad section state LEDs don’t respond if you send back their respective MIDI messages to the controller. So I was trying to see if one could at least toggle the deck3/4 indicator and accept that the pads cannot be latched. But, as it turns out, sending the deck3/4-button sequences back to the controller not only toggles the deck indicator lights, but also switches the complete pad section into the appropriate state. So that is gonna make things for us much easier.

For the implementation, one would simply bind the deck3 button input and send the deck3/4 MIDI message back to the controller. That latches the whole deck into its alternative mode.

**Comment by Lykos153** [comment]
That's real good news! I didn't even try to latch it via MIDI message. I'm glad you found this!
